_partial_: false
output_transform:
  path: atria_metrics.instance_classification.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
is_multilabel: false
device: cpu
skip_unrolling: false
module: ignite.metrics.accuracy.Accuracy
_target_: atria_metrics.registry.registry_groups.MetricBuilder
