_partial_: false
threshold: 0.5
output_transform:
  path: atria_metrics.qa.output_transforms._anls_output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
module: atria_metrics.qa.anls.ANLS
_target_: atria_metrics.registry.registry_groups.MetricBuilder
