_partial_: false
num_classes: ???
average: recall
output_transform:
  path: atria_metrics.instance_classification.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
skip_unrolling: true
module: ignite.metrics.confusion_matrix.ConfusionMatrix
_target_: atria_registry.module_builder.ModuleBuilder
