_partial_: false
average: recall
output_transform:
  path: atria_metrics.instance_classification.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
skip_unrolling: true
module: ignite.metrics.confusion_matrix.ConfusionMatrix
_target_: atria_metrics.registry.registry_groups.MetricBuilder
