_partial_: false
output_transform:
  path: atria_metrics.layout.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
average: false
is_multilabel: false
device: cpu
module: atria_metrics.layout.recall.LayoutRecall
_target_: atria_metrics.registry.registry_groups.MetricBuilder
