_partial_: false
output_transform:
  path: atria_metrics.layout.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
module: atria_metrics.layout.f1_score.f1_score
_target_: atria_registry.module_builder.ModuleBuilder
