_partial_: false
metric_func: seqeval.metrics.classification_report
output_transform:
  path: atria_metrics.token_classification.output_transforms._output_transform
  _target_: hydra_zen.funcs.get_obj
device: cpu
scheme: IOB2
module: atria_metrics.token_classification.seqeval.seqeval_classification_metric
_target_: atria_metrics.registry.registry_groups.MetricBuilder
